### ISSUE TITLE
pmap args out of order segy_scan

### ISSUE THREAD

**Issue by cdane** [slimgroup/SegyIO.jl#2]
Hi,

I could be missing something but it looks like the arguments in the pmap call in segy_scan are out of order. E.g. to get it to run, on line 31 I changed:

s = pmap(pool, run_scan, files_sort)
to 
s = pmap(run_scan, pool, files_sort)

Thanks,
Dane

**Comment by henryk-modzelewski** [comment]
Thanks for spotting it. Fixed in v0.7.2.
